language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  global:
    - SKIP_VENV_INIT=y

install:
  - pip install -r requirements/development.txt
  - pip freeze # Print versions of all installed packages for logging purposes
script:
  - ./bin/pytest.sh
